site_name: 网站
site_url: https://GuChL9/github.io/site-test/
site_description: 基础医学网站
repo_name: ZJU-BMS
repo_url: https://github.com/GuChL9/site-test
edit_uri: tree/master/docs

theme:
  name: material
  language: 'zh'
  logo: assets/logo_white.png

  #主题切换
  palette:

    #下面这一个是自适应，但我觉得没用
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: custom

    # 日间模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # 夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  


  features:
    - content.code.annotate
    - content.action.edit
    - navigation.instant
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
# 顶部导航栏
    - navigation.tabs
    - navigation.tracking
# 返回顶部按钮
    - navigation.top
# 章节索引页面
    - navigation.indexes
# 静态导航栏
#    - navigation.tabs.sticky
# 自动展开左侧列表
#    - navigation.sections
# 激活导航路径后，痕迹导航将呈现在每个页面的标题上方，这可能会使用户在屏幕较小的设备上访问您的文档时更容易找到方向。将以下行添加到
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.annotate    
    - content.action.edit
# 评论
  custom_dir: overrides


#导航
nav:
  - 首页:
    - index.md
    - 制作组留言: homepage/about_us.md
  - 紫金港速通: 
    - 紫金港速通: freshman/freshman.md
  - 通识类课程: 
    - tongshi/index.md
    - 军体类: 
      - tongshi/jt/jt.md
    - 思政类: 
      - tongshi/sz/sz.md
    - 通识选修类: 
      - tongshi/tsxx/tsxx.md
    - 通识必修类: 
      - tongshi/tsbx/tsbx.md
  - 专业类课程: 
    - zhuanye/index.md
    - 专业模块类: 
      - zhuanye/zymk/index.md
      - 生物类课程:
        - 医学生命基础: zhuanye/zymk/swl/yxsmjc/yxsmjc.md
        - 医学科学素养Ⅰ: zhuanye/zymk/swl/yxkxsy1/yxkxsy1.md
        - 医学科学英语基础: zhuanye/zymk/swl/yxkxyyjc/yxkxyyjc.md
        - 基础医学科学研究技能Ⅰ: zhuanye/zymk/swl/jcyxkxyjjn1/jcyxkxyjjn1.md
        - 细胞与生物分子Ⅰ: zhuanye/zymk/swl/xbyswfz1/xbyswfz1.md
        - 细胞与生物分子Ⅱ: zhuanye/zymk/swl/xbyswfz2/xbyswfz2.md
        - 遗传与发育Ⅰ: zhuanye/zymk/swl/ycyfy1/ycyfy1.md
        - 遗传与发育Ⅱ: zhuanye/zymk/swl/ycyfy2/ycyfy2.md
      - 基础医学类课程: 
        - 人体结构与功能学: zhuanye/zymk/jcyxl/rtjgygnx/index.md
        - 感染与免疫学: zhuanye/zymk/jcyxl/grymyx.md
        - 疾病基础: zhuanye/zymk/jcyxl/jbjc.md
        - 基础药理学: zhuanye/zymk/jcyxl/jcylx.md
        - 神经科学: zhuanye/zymk/jcyxl/sjkx.md
      - 公共卫生与预防医学类课程:
        - 实验动物与伦理学: zhuanye/zymk/ggwsyyfyxl/sydwyllx.md
        - 医学科学素养Ⅱ: zhuanye/zymk/ggwsyyfyxl/yxkxsy2.md
        - 临床流行病与循证医学: zhuanye/zymk/ggwsyyfyxl/lclxbyxzyx.md
      - 临床医学类课程:
        - 重要疾病的临床与研究Ⅰ: zhuanye/zymk/lcyx/zyjbdlcyyj1.md
        - 重要疾病的临床与研究Ⅱ: zhuanye/zymk/lcyx/zyjbdlcyyj2.md
        - 重要疾病的临床与研究Ⅲ: zhuanye/zymk/lcyx/zyjbdlcyyj3.md
      - 交叉性课程:
        - 医学生物物理学: 
          - zhuanye/zymk/jcx/yxswwlx/index.md
        - 脑与脑机融合: zhuanye/zymk/jcx/nynjrh.md
        - 医学大数据与应用: zhuanye/zymk/jcx/yxdsjyyy.md
    - 专业方向课程:
      - zhuanye/zyfx/index.md
      - 分子肿瘤方向:
        - 肿瘤生物学: 
          - zhuanye/zyfx/fzzl/肿瘤生物学/index.md
        - 肿瘤研究策略与应用: 
          - zhuanye/zyfx/fzzl/肿瘤研究策略与应用/index.md
        - 临床肿瘤学概论: 
          - zhuanye/zyfx/fzzl/临床肿瘤学概论/index.md
      - 感染与免疫学:
        - 微生物学与免疫学前沿技术: zhuanye/zyfx/grymyx/wswxymyxqyjs/index.md
        - 重要传染病的防治基础: zhuanye/zyfx/grymyx/zycrbdfzjc/index.md
        - 临床免疫学: zhuanye/zyfx/grymyx/lcmyx/index.md
    - 专业选修类: 
      - zhuanye/zyxx/index.md
      - 物理化学: zhuanye/zyxx/wlhx/wlhx.md
      - 新药研发: zhuanye/zyxx/xyyf.md
      - 法理学: zhuanye/zyxx/flx.md
      - 管理学: zhuanye/zyxx/glx.md
      - 卫生学: zhuanye/zyxx/wsx.md
      - 概率论与数理统计: zhuanye/zyxx/gllysltj/index.md
    - 实践教学环节: 
      - zhuanye/sjjx/index.md
      - 基础医学科学研究技能Ⅱ: zhuanye/sjjx/jcyxkxyjjn2/index.md
      - 基础医学科研实践: zhuanye/sjjx/jcyxkysj/index.md
      - 基础医学教育见习: zhuanye/sjjx/jcyxjyjx/index.md
      - 临床实习: zhuanye/sjjx/lcsx/index.md
    - 个性修读类: 
      - zhuanye/gxxd/gxxd.md
  - 本科生轮转: 
    - 本科生轮转: rotation/rotation.md
  - 求科强基政策收集 :
    - zhengce/index.md
    - 政策: zhengce/zhengce.md
  - 飞跃专题:
    - 飞跃手册:
      - 飞跃: feiyue/feiyue.md
  - 后记:
    - 后记: postscript/postscript.md

#搜索功能
plugins:
  - search

#这个地方是页面最下方放友情链接的，需要一个图标icon和一个链接link
extra:
  social:
    - icon: material/web-check
      link: https://bms.zju.edu.cn/

#这个是版权横幅
copyright: Copyright &copy; 2024-2025 基础医学飞跃手册编委会

markdown_extensions:
#  - toc:
#      permalink: true
#      toc_depth: 4
#  - meta
#  - def_list
#  - attr_list
#  - md_in_html
#  - sane_lists
#  - admonition
#  - pymdownx.keys
#  - pymdownx.mark
#  - pymdownx.tilde
#  - pymdownx.critic
#  - pymdownx.details
#  - pymdownx.snippets
#  - pymdownx.magiclink
#  - pymdownx.superfences
#  - pymdownx.inlinehilite
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
# 选项卡功能
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
